#pragma once

#include "types.h"

/*!
 * Base class for objects identified by a GUID.
 */
class IdentifyableObject
{
	private:
		guid_t m_guid;

	public:
		/*!
		 * Create this object with a GUID generated by the GUIDGenerator singleton
		 * class.
		 */
		IdentifyableObject();
		virtual ~IdentifyableObject();

		/*!
		 * Get the GUID of this object.
		 */
        guid_t getGUID(void) const
		{
			return m_guid;
		}
};
