/*
 * Schlangenprogrammiernacht: A programming game for GPN18.
 * Copyright (C) 2018  bytewerk
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include "types.h"

/*!
 * Base class for objects identified by a GUID.
 */
class IdentifyableObject
{
	private:
		guid_t m_guid;

	public:
		/*!
		 * Create this object with a GUID generated by the GUIDGenerator singleton
		 * class.
		 */
		IdentifyableObject();
		virtual ~IdentifyableObject();

		/*!
		 * Get the GUID of this object.
		 */
		guid_t getGUID(void) const
		{
			return m_guid;
		}
};
